## What is NumPy?

NumPy (Numerical Python) is a Python library used for:
- Numerical computations
- Working with arrays
- Scientific and data science tasks
- NumPy stands for Numerical Python.

## Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

NumPy provides various math functions for calculations like addition, algebra, and data analysis.

Arrays are very frequently used in data science, where speed and resources are very important.

NumPy provides:
- Fast operations
- Multi-dimensional arrays
- Mathematical functions
- Memory efficiency

It is widely used in:
- Data Science
- Machine Learning
- Scientific Computing



## Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.




## NumPy Documentation

NumPy's documentation, reference manuals, and user guide can be found at these links:

- https://numpy.org/doc/stable/user/absolute_beginners.html
- https://numpy.org/devdocs/dev/index.html


## NumPy Codebase 
 
 NumPy's source code can be found at this github repository: https://github.com/numpy/numpy



## NumPy Arrays vs Python Lists

| Python List | NumPy Array |
|------------|-------------|
| Slow | Fast |
| Can store mixed types | Stores same data type |
| Less memory efficient | More memory efficient |


## Installing NumPy

NumPy is usually pre-installed with Anaconda.

If required, it can be installed using pip.

cmd - `pip install numpy`

In [1]:
!pip install numpy

In [2]:
import numpy as np
print(np.__version__)


2.3.1


## Creating NumPy Arrays

NumPy is used to work with arrays. The array object in NumPy is called `ndarray`.

NumPy arrays are created using:
- array()
- arange()
- zeros()
- ones()



In [3]:
# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray
# Create a NumPy array from a Python list
list_1 = [1,2,3,4,5]
arr = np.array(list_1)
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
# Create an array using arange()
arr = np.arange(1,11)
print(arr)

# Create an array filled with zeros
zeros_arr = np.zeros(5)
print(zeros_arr)

# Create an array filled with ones
ones_arr = np.ones(5)
print(ones_arr)



[ 1  2  3  4  5  6  7  8  9 10]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


## Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.

#### 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [12]:
# Create a 0-D array
arr = np.array(12)
print(arr)

12


### 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [14]:
# Create a 1-D array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [15]:
# Create a 2-D array containing two arrays
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [18]:
# Create a 3-D array with two 2-D arrays
arr = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [7,8,9],
            [10,11,12]
        ]
    ]
)
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


### Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.



In [21]:
# Create an array with 5 dimensions and verify that it has 5 dimensions

multi_Arr = np.array([1,2,3,4], ndmin = 5)
print(multi_Arr)
print(multi_Arr.ndim)

[[[[[1 2 3 4]]]]]
5


## Array Attributes

NumPy arrays have useful attributes such as:
- shape
- size
- ndim
- dtype


In [22]:
# Create an array
arr = np.array([[1,2,3],[4,5,6]])

# Print shape of array
print(arr.shape)

# Print number of dimensions
print(arr.ndim)

# Print data type
print(arr.dtype)

# Print size of array
print(arr.size)

(2, 3)
2
int64
6


## NumPy Array Indexing 

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.


Indexing is used to:
- Access individual elements
- Modify elements

NumPy uses zero-based indexing.


## NumPy Array Slicing 

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: `[start:end]`.

We can also define the step, like this: `[start:end:step]`.

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1


In [24]:
# Create a 1D NumPy array
arr = np.array([10,20,30,40,50])

# Access first element
print(arr[0])


# Access last element
print(arr[-1])



10
50


In [ ]:
# Slice first few elements
print(arr[:3]) # 0,1,2


# Slice middle elements
print(arr[2:4]) # 2,3 and excuded 4


[10 20 30]
[30 40]


### 2D Arrays

NumPy supports multi-dimensional arrays.

### Indexing in 2D Arrays

Access elements using:
array[row, column]

### Slicing in 2D Arrays

Slicing works on rows and columns.



In [41]:
# Create a 2D array
arr_2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
)
print(arr_2d)
print(arr_2d.ndim)

# Access a specific element
print(arr_2d[1,1])


# Access an entire row
print(arr_2d[1])


# Access an entire column
print(arr_2d[:,2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
5
[4 5 6]
[3 6 9]


In [45]:
# Slice rows
print(arr_2d[0:2])

# Slice columns
print(arr_2d[:,0:2])


# Slice sub-matrix
print(arr_2d[0:2,1:3])


[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [7 8]]
[[2 3]
 [5 6]]


### 3D Arrays
A 3D array is an array of 2D arrays (think of it as layers → rows → columns).

### Indexing in 3D Arrays

Access elements using:
array[layer, row, column]

### Slicing in 3D Arrays

Slicing can be applied to:
- Layers
- Rows
- Columns

Multiple dimensions can be sliced at the same time.




In [59]:
arr_3d = np.arange(1,49).reshape(3,4,4)
print(arr_3d)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]]


In [55]:
print(arr_3d[1,2:4,1:3])

[[26 27]
 [30 31]]


In [48]:
# Access an element from the first layer
print(arr_3d[0,1,2])


# Access an element from a specific row and column in another layer
print(arr_3d[1,2,3])


7
24


In [52]:
# Slice specific layers
print(arr_3d[1])


# Slice rows and columns from a specific layer
print(arr_3d[1,:,0:3])


# Slice a sub-block from the 3D array
print(arr_3d[1,1:3,1:3])


[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[13 14 15]
 [17 18 19]
 [21 22 23]]
[[18 19]
 [22 23]]
