## Linear Algebra 

Linear Algebra is the branch of mathematics that focuses on the study of vectors, vector spaces, matrices, and linear transformations. 

It enables efficient modeling and computation for systems of linear equations, engineering, physics, and computer science.

It deals with linear equations, linear functions, and their representations through matrices and determinants.

It is the basic concept for machine learning and data science.

Link for Resources: https://www.geeksforgeeks.org/maths/linear-algebra/

Linear Algebra with Numpy : https://www.tutorialspoint.com/numpy/numpy_linear_algebra.htm

## Linear Algebra in Numpy

The Linear Algebra module of NumPy offers various methods to apply linear algebra on any numpy array. One can find:

- rank, determinant, trace, etc. of an array.
- eigen values of matrices
- matrix and vector products (dot, inner, outer,etc. product), matrix exponentiation
- solve linear or tensor equations and much more!


NumPy provides linear algebra functions through:
- numpy.linalg module
- Array-based operations

These functions are optimized and fast.

## Vectors and Matrices

- A vector is a 1D array
- A matrix is a 2D array

These are basic building blocks of linear algebra.


In [1]:
import numpy as np

In [2]:
# Create a vector (1D array)
vector = np.array([1,2,3])
print(vector)
print()

# Create a matrix (2D array)
matrix = np.array([
    [1,2],
    [3,4]
])
print(matrix)


[1 2 3]

[[1 2]
 [3 4]]


## Matrix Addition and Subtraction

Matrices of the same shape can be:
- Added
- Subtracted


In [5]:
# Create two matrices of same shape
arr_1 = np.array([[1,2],[3,5]])
arr_2 = np.array([[5,6],[7,8]])

# Perform matrix addition
print(arr_1 + arr_2)

print()

# Perform matrix subtraction
print(arr_2 - arr_1)


[[ 6  8]
 [10 13]]

[[4 4]
 [4 3]]


## Matrix Multiplication

There are two types:
- Element-wise multiplication
- Matrix multiplication (dot product)


In [6]:
# Create two matrices
arr_1 = np.array([[1,2],[3,5]])
arr_2 = np.array([[5,6],[7,8]])



# Perform element-wise multiplication
print(arr_1 * arr_2)


[[ 5 12]
 [21 40]]


$$
A =
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{bmatrix}
\quad
B =
\begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22}
\end{bmatrix}
$$


$$
A.B =
\begin{bmatrix}
a_{11}b_{11} + a_{12}b_{21} & a_{11}b_{12} + a_{12}b_{22} \\
a_{21}b_{11} + a_{22}b_{21} & a_{21}b_{12} + a_{22}b_{22}
\end{bmatrix}
$$


In [7]:
# Perform matrix multiplication using dot or @ operator
print(np.dot(arr_1, arr_2))


[[19 22]
 [50 58]]


In [8]:
print(arr_1 @ arr_2)

[[19 22]
 [50 58]]


## Transpose of a Matrix

Transpose flips rows into columns.


In [10]:
# Create a matrix
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix)
print()


# Find transpose of the matrix
print(matrix.T)


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


## Identity Matrix

An identity matrix has:
- 1s on the diagonal
- 0s elsewhere


In [11]:
# Create an identity matrix
identity = np.eye(3)
print(identity)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Determinant of a Matrix

A matrix determinant is a special number that can be calculated from a square matrix. It provides important information about the matrix, such as whether the matrix is invertible.

The determinant of a matrix is a single number, not a matrix, and it can be used to solve systems of linear equations, find eigenvalues, and more.

For example, the determinant of a 2x2 matrix A is calculated as follows −

Let

$$
A =
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$

The determinant of $A$ is:

$$
\det(A) = ad - bc
$$



In [13]:
# Create a square matrix
sqr_matrix = np.array([[1,2], [3,4]])


# Calculate determinant
det = np.linalg.det(sqr_matrix)
print(det)

-2.0000000000000004


## Inverse of a Matrix

Matrix inversion is a process of finding a matrix, called the inverse matrix, which, when multiplied with the original matrix, produces the identity matrix. 

The identity matrix is a square matrix with ones on the main diagonal and zeros elsewhere.

Not all matrices have inverses. A matrix must be square (having the same number of rows and columns) and its determinant must be non-zero to have an inverse.

If A is a square matrix, its inverse is denoted by A-1 and is defined by the following property −

` A . A-1 = A-1 . A = I`

Where I is the identity matrix of the same dimension as A. This property means that when a matrix is multiplied by its inverse, the result is the identity matrix.


In [14]:
# Create a square matrix
sqr_matrix = np.array([[1,2], [3,4]])


# Calculate inverse of the matrix
inverse = np.linalg.inv(sqr_matrix)
print(inverse)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
print(np.round(np.dot(sqr_matrix, inverse), 10))

[[1. 0.]
 [0. 1.]]


In [24]:
det_0 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
det = np.linalg.det(det_0)
print(det)

0.0


In [ ]:
inverse_1 = np.linalg.inv(det_0) # throws an error since detterminant is 0 so cannot get its inverse matrix

LinAlgError: Singular matrix

## Solving Linear Equations

Linear equations are mathematical equations that involve linear terms, meaning the highest power of the variable is one.

A system of linear equations can be expressed as a set of equations with multiple variables. The goal is to find the values of these variables that satisfy all equations simultaneously.

In matrix form, a system of linear equations can be represented as − 

`A * x = b`

Here,

- A: A matrix representing the coefficients of the linear equations.
- x: A column vector representing the unknown variables.
- b: A column vector representing the constants on the right-hand side of the equations.

The goal is to find the vector x, which contains the values of the unknown variables. NumPy provides methods to solve such systems of equations using matrix operations.


3x + 2y = 5

x + 2y = 5

In [28]:
# Define matrix A
A = np.array([[3,2], [1,2]])


# Define vector b
b = np.array([5,5])


# Solve Ax = b
x = np.linalg.solve(A,b)

print(x)


[0.  2.5]


Solve : 

2x+y=7

x+3y=11​

Solve: ​

x+y+z=6

2x−y+z=3

x+2y+3z=14
	​


## Eigenvalues and Eigenvectors

Eigenvalues are special numbers associated with a matrix that provide important information about the matrix's properties.

Eigenvectors are special vectors associated with a matrix that provide information about the matrix's properties.

In the context of linear algebra, if A is a square matrix, an eigenvalue is a scalar such that there exists a non-zero vector v (called an eigenvector) satisfying the equation −

` Av = v`


Eigenvalues and eigenvectors are important in:
- PCA
- Dimensionality reduction
- ML algorithms


In [29]:
# Create a square matrix
sqr_matrix = np.array([[4, -2], [1,1]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(sqr_matrix)

print("Eigen Values", eigenvalues)
print("Eigen Vectors", eigenvectors)

Eigen Values [3. 2.]
Eigen Vectors [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
