## Common Mathematical Operations in NumPy

NumPy supports element-wise mathematical operations such as:
- Addition
- Subtraction
- Multiplication
- Division


In [1]:
import numpy as np

In [4]:
# Create two NumPy arrays

arr_1 = np.array([10,20,30,40,50])
arr_2 = np.array([1,2,3,4,5])

# Perform element-wise addition
print(arr_1 + arr_2) # arr_1[0] + arr_2[0] 

# Perform element-wise subtraction
print(arr_1 - arr_2)


# Perform element-wise multiplication
print(arr_1 * arr_2)


# Perform element-wise division
print(arr_1 / arr_2)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


## Universal Functions (ufuncs)

NumPy ufuncs (universal functions) are fast, vectorized functions that perform element-wise operations on NumPy arrays.

They are highly optimized and support features like broadcasting and automatic type handling. NumPy includes many ufuncs for arithmetic, trigonometry, statistics, etc,

NumPy provides universal functions that operate on arrays:
- sqrt()
- log()
- exp()
- power()


In [9]:
# Create a NumPy array
arr = np.array([1,4,9,16,25])

# Calculate square root
print(np.sqrt(arr))


# Calculate logarithm
print(np.log(arr))


# Calculate exponential
print(np.exp(arr))

# calculate power 
print(np.power(arr, 2))


[1. 2. 3. 4. 5.]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
[  1  16  81 256 625]


## Trigonometric Functions

NumPy supports trigonometric functions such as:
- sin()
- cos()
- tan()

Angles are in radians.


# Convert degrees into radians

radians_values  = pi/180 * degree_values 

`If degree = 90, radian = (3.14/180) * 90 `

In [17]:
# Create a NumPy array of angles (in radians)
angles = np.array([0, np.pi / 2, np.pi ])

# Calculate sine values
print(np.sin(angles)) 

# Calculate cosine values
print(np.cos(angles))


[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [21]:
degree_arr = np.rad2deg(angles)
print(degree_arr)

radian_value = np.deg2rad(degree_arr)
print(radian_value)

[  0.  90. 180.]
[0.         1.57079633 3.14159265]


## Aggregation Functions

Aggregation functions summarize data:
- sum()
- min()
- max()
- mean()


In [30]:
# Create a NumPy array
arr = np.array([10,20,30,40,50])

# Calculate sum
print(np.sum(arr))


# Calculate minimum value
print(np.min(arr))


# Calculate maximum value
print(np.max(arr))


# Calculate mean
print(np.mean(arr))


150
10
50
30.0


## Statistical Functions

NumPy provides several statistical functions to calculate properties like mean, median, variance, and range. These functions operate element-wise and along specified axes, making analysis of arrays fast and efficient.

NumPy provides statistical functions to analyze data:
- median()
- std()
- var()


$$
\sigma = \sqrt{\frac{1}{N}\sum_{i=1}^{N}(x_i - \mu)^2}
$$


In [33]:
# Create a NumPy array
arr = np.array([65,70,80,78,98])

# Calculate median
print(np.median(arr))

# Calculate standard deviation
print(np.std(arr))

# Calculate variance
print(np.var(arr))



78.0
11.285388783732706
127.35999999999999


## Sorting Data

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called `sort()`, that will sort a specified array.


In [38]:
# Create a NumPy array
arr = np.array([3,2,1,5,6,4,0,10,15,11])

# Sort the array
print(np.sort(arr))
print(np.flip(np.sort(arr)))


[ 0  1  2  3  4  5  6 10 11 15]
[15 11 10  6  5  4  3  2  1  0]


In [39]:
# Sort an 2-D Array
arr = np.array([[3,2,1, 9], [5,0,7,1]])

print(np.sort(arr))

[[1 2 3 9]
 [0 1 5 7]]


## Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the `where()` method.



NumPy can find unique values in an array.


In [43]:
# Search 

arr = np.array([1,2,3,4,5,6,7,4,6,7])
print(arr)

print(np.where(arr == 4))

[1 2 3 4 5 6 7 4 6 7]
(array([3, 7]),)


In [ ]:
index_even_filter = np.where(arr%2 == 0) # which returns index of even number
print(index_even_filter)

(array([1, 3, 5, 7, 8]),)


## Finding Unique Values

NumPy can find unique values in an array.


In [45]:
# Create a NumPy array with duplicate values
arr = np.array([1,2,3,4,5,6,7,4,6,7])


# Find unique elements
print(np.unique(arr))


[1 2 3 4 5 6 7]


## Cumulative Operations

Cumulative functions apply operations progressively:
- cumsum()
- cumprod()


In [47]:
# Create a NumPy array
arr = np.array([1, 2, 3 ,4, 5])


# Calculate cumulative sum
print(np.cumsum(arr))


# Calculate cumulative product
print(np.cumprod(arr))

[ 1  3  6 10 15]
[  1   2   6  24 120]


In [49]:
## Normal distribution 

from numpy import random

x = random.normal(loc = 1, size = (2,3), scale = 2)
print(x)

[[ 1.06976776  2.04189314 -3.49472316]
 [-1.82236957 -1.80804711  1.81577548]]
